branches:
  only:
    - master

language: python
python:
  - "3.4"
  - "nightly"

install:
  - pip install -U -r test_requirements.txt

before_script:
  - pip install -U -e .
script:
  - py.test tests --doctest-modules --pep8 aorn -v --cov aorn --cov-report term-missing
after_success:
  - coveralls

